# Generated by Django 3.1.2 on 2020-10-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_city',
        ),
    ]
